import AsyncStorage from '@react-native-async-storage/async-storage';
import { AccessibilityInfo, AppState, PixelRatio, Platform } from 'react-native';
import { ACE_TRIAL, CROSS_SECTION_JOURNEYS, MBW_SECTIONS } from './MBWSovereignConstitution';
const STORAGE_KEY='@MBW:SOVEREIGN:RUNTIME:V1';
const runtime={booted:false,appState:AppState.currentState,reducedMotion:false,sessionStartedAt:Date.now(),sessionDepth:0,lastRoute:null,routes:[],milestones:{},events:[],deviceMode:'BALANCED',continuityLoaded:false};
function hashText(value){let hash=2166136261;for(let i=0;i<value.length;i+=1){hash^=value.charCodeAt(i);hash=Math.imul(hash,16777619);}return Math.abs(hash>>>0);}
function timeBand(date=new Date()){const hour=date.getHours();if(hour>=5&&hour<12)return'MORNING';if(hour>=12&&hour<18)return'DAY';if(hour>=18&&hour<22)return'EVENING';return'NIGHT';}
function chooseDeviceMode(){const density=PixelRatio.get();if(Platform.OS!=='android')return'BALANCED';if(density>=3)return'HIGH';if(density<=1.5)return'SAFE';return'BALANCED';}
function rarityFor(routeName,dayKey){const value=hashText(`${routeName}:${dayKey}`)%1000;if(value<5)return'ACE';if(value<25)return'ROYAL';if(value<90)return'RARE';if(value<260)return'UNCOMMON';return'COMMON';}
async function persist(){const payload={lastRoute:runtime.lastRoute,routes:runtime.routes.slice(-40),milestones:runtime.milestones,events:runtime.events.slice(-120)};await AsyncStorage.setItem(STORAGE_KEY,JSON.stringify(payload));}
async function restore(){try{const raw=await AsyncStorage.getItem(STORAGE_KEY);if(raw){const data=JSON.parse(raw);runtime.lastRoute=data.lastRoute??null;runtime.routes=Array.isArray(data.routes)?data.routes.slice(-40):[];runtime.milestones=data.milestones&&typeof data.milestones==='object'?data.milestones:{};runtime.events=Array.isArray(data.events)?data.events.slice(-120):[];}}catch(error){runtime.events.push({type:'CONTINUITY_RESTORE_ERROR',at:Date.now(),message:String(error)});}finally{runtime.continuityLoaded=true;}}
export async function bootMBWSovereignRuntime(){if(runtime.booted)return runtime;runtime.booted=true;runtime.deviceMode=chooseDeviceMode();try{runtime.reducedMotion=await AccessibilityInfo.isReduceMotionEnabled();}catch(error){runtime.reducedMotion=false;}await restore();AppState.addEventListener('change',async(nextState)=>{runtime.appState=nextState;if(nextState!=='active'){try{await persist();}catch(error){runtime.events.push({type:'CONTINUITY_SAVE_ERROR',at:Date.now(),message:String(error)});}}});return runtime;}
export function resolveMBWScene(routeName){const section=MBW_SECTIONS[routeName]||MBW_SECTIONS.MainHub;const now=new Date();const dayKey=`${now.getFullYear()}-${now.getMonth()+1}-${now.getDate()}`;return Object.freeze({routeName,timeBand:timeBand(now),sessionDepth:runtime.sessionDepth,deviceMode:runtime.deviceMode,reducedMotion:runtime.reducedMotion,rarity:rarityFor(routeName,dayKey),visualEngine:section.visual,functionalEngine:section.functional,journey:section.journey,previousRoute:runtime.lastRoute});}
export function enterMBWRoute(routeName){runtime.sessionDepth+=1;runtime.lastRoute=routeName;runtime.routes.push({routeName,at:Date.now()});runtime.routes=runtime.routes.slice(-40);runtime.events.push({type:'ROUTE_ENTER',routeName,at:Date.now()});runtime.events=runtime.events.slice(-120);persist().catch(()=>{});return resolveMBWScene(routeName);}
export function recordMBWEvent(type,payload={}){runtime.events.push({type,payload,at:Date.now()});runtime.events=runtime.events.slice(-120);persist().catch(()=>{});}
export function registerACEMilestone(name,value=true){runtime.milestones[name]=value;const completed=ACE_TRIAL.milestones.filter(item=>runtime.milestones[item]).length;recordMBWEvent('ACE_MILESTONE',{name,completed,total:ACE_TRIAL.milestones.length});return{completed,total:ACE_TRIAL.milestones.length,ultraAceReady:completed===ACE_TRIAL.milestones.length};}
export function resolveCrossSectionJourney(routeName){return CROSS_SECTION_JOURNEYS.find(journey=>journey.includes(routeName))||[routeName,'MainHub'];}
export function getMBWSovereignRuntimeSnapshot(){return JSON.parse(JSON.stringify(runtime));}
