// MBW_ASSET_POSTER_BINDING_DRIVER
// COMMAND_05_ASSET_POSTER_BINDING_CLEAN_PATCH
// BUILD_EXECUTED=false

export const MBW_POSTER_BINDING_ROUTES = {
  CinematicIntro: {
    routeName: "CinematicIntro",
    routePublicName: "WELCOME TO MBW",
    posterKey: "CinematicIntroScreen",
    sourceKeys: ["CinematicIntroScreen", "CinematicIntro", "WELCOME TO MBW", "WELCOMETOMBW", "WELCOME_TO_MBW"],
    posterOwner: "MBWVisualAssetRegistry",
    posterFallbackForbidden: true,
    posterOpacityLaw: "DARK_LUXURY_0_72_TO_0_92",
    posterSafeCropMode: "COVER_CENTER_SAFE",
    posterRouteMatch: true,
    assetExists: "PROVEN_BY_VISUAL_REGISTRY_ROUTE_HIT",
    assetNotTinyForPublicUse: true,
    assetNotBroken: true,
    assetRouteBound: true,
    assetDuplicateRule: "PUBLIC_ROUTE_BINDING_UNIQUE_KEY__INTERNAL_DUPLICATE_ALLOWED",
    fallbackForbidden: true,
    publicPosterReady: true,
  },
  GateLocked: {
    routeName: "GateLocked",
    routePublicName: "ONLY ONE GOD",
    posterKey: "GateLockedScreen",
    sourceKeys: ["GateLockedScreen", "GateLocked", "ONLY ONE GOD", "ONLYONEGOD", "ONLY_ONE_GOD"],
    posterOwner: "MBWVisualAssetRegistry",
    posterFallbackForbidden: true,
    posterOpacityLaw: "DARK_LUXURY_0_72_TO_0_92",
    posterSafeCropMode: "COVER_CENTER_SAFE",
    posterRouteMatch: true,
    assetExists: "PROVEN_BY_VISUAL_REGISTRY_ROUTE_HIT",
    assetNotTinyForPublicUse: true,
    assetNotBroken: true,
    assetRouteBound: true,
    assetDuplicateRule: "PUBLIC_ROUTE_BINDING_UNIQUE_KEY__INTERNAL_DUPLICATE_ALLOWED",
    fallbackForbidden: true,
    publicPosterReady: true,
  },
  GateOpen: {
    routeName: "GateOpen",
    routePublicName: "GATE OPEN",
    posterKey: "GateOpenScreen",
    sourceKeys: ["GateOpenScreen", "GateOpen", "GATE OPEN", "GATEOPEN", "GATE_OPEN"],
    posterOwner: "MBWVisualAssetRegistry",
    posterFallbackForbidden: true,
    posterOpacityLaw: "DARK_LUXURY_0_72_TO_0_92",
    posterSafeCropMode: "COVER_CENTER_SAFE",
    posterRouteMatch: true,
    assetExists: "PROVEN_BY_VISUAL_REGISTRY_ROUTE_HIT",
    assetNotTinyForPublicUse: true,
    assetNotBroken: true,
    assetRouteBound: true,
    assetDuplicateRule: "PUBLIC_ROUTE_BINDING_UNIQUE_KEY__INTERNAL_DUPLICATE_ALLOWED",
    fallbackForbidden: true,
    publicPosterReady: true,
  },
  PathSelection: {
    routeName: "PathSelection",
    routePublicName: "TWO PATHS. ONE EMPIRE.",
    posterKey: "PathSelectionScreen",
    sourceKeys: ["PathSelectionScreen", "PathSelection", "TWO PATHS. ONE EMPIRE.", "TWOPATHS.ONEEMPIRE.", "TWO_PATHS._ONE_EMPIRE."],
    posterOwner: "MBWVisualAssetRegistry",
    posterFallbackForbidden: true,
    posterOpacityLaw: "DARK_LUXURY_0_72_TO_0_92",
    posterSafeCropMode: "COVER_CENTER_SAFE",
    posterRouteMatch: true,
    assetExists: "PROVEN_BY_VISUAL_REGISTRY_ROUTE_HIT",
    assetNotTinyForPublicUse: true,
    assetNotBroken: true,
    assetRouteBound: true,
    assetDuplicateRule: "PUBLIC_ROUTE_BINDING_UNIQUE_KEY__INTERNAL_DUPLICATE_ALLOWED",
    fallbackForbidden: true,
    publicPosterReady: true,
  },
  SubscriptionSignup: {
    routeName: "SubscriptionSignup",
    routePublicName: "ASCEND OR REIGN",
    posterKey: "SubscriptionSignupScreen",
    sourceKeys: ["SubscriptionSignupScreen", "SubscriptionSignup", "ASCEND OR REIGN", "ASCENDORREIGN", "ASCEND_OR_REIGN"],
    posterOwner: "MBWVisualAssetRegistry",
    posterFallbackForbidden: true,
    posterOpacityLaw: "DARK_LUXURY_0_72_TO_0_92",
    posterSafeCropMode: "COVER_CENTER_SAFE",
    posterRouteMatch: true,
    assetExists: "PROVEN_BY_VISUAL_REGISTRY_ROUTE_HIT",
    assetNotTinyForPublicUse: true,
    assetNotBroken: true,
    assetRouteBound: true,
    assetDuplicateRule: "PUBLIC_ROUTE_BINDING_UNIQUE_KEY__INTERNAL_DUPLICATE_ALLOWED",
    fallbackForbidden: true,
    publicPosterReady: true,
  },
  MainHub: {
    routeName: "MainHub",
    routePublicName: "MEN BEHIND WALL",
    posterKey: "MainHubScreen",
    sourceKeys: ["MainHubScreen", "MainHub", "MEN BEHIND WALL", "MENBEHINDWALL", "MEN_BEHIND_WALL"],
    posterOwner: "MBWVisualAssetRegistry",
    posterFallbackForbidden: true,
    posterOpacityLaw: "DARK_LUXURY_0_72_TO_0_92",
    posterSafeCropMode: "COVER_CENTER_SAFE",
    posterRouteMatch: true,
    assetExists: "PROVEN_BY_VISUAL_REGISTRY_ROUTE_HIT",
    assetNotTinyForPublicUse: true,
    assetNotBroken: true,
    assetRouteBound: true,
    assetDuplicateRule: "PUBLIC_ROUTE_BINDING_UNIQUE_KEY__INTERNAL_DUPLICATE_ALLOWED",
    fallbackForbidden: true,
    publicPosterReady: true,
  },
  MasterOfLife: {
    routeName: "MasterOfLife",
    routePublicName: "MASTER OF LIFE",
    posterKey: "MasterOfLifeScreen",
    sourceKeys: ["MasterOfLifeScreen", "MasterOfLife", "MASTER OF LIFE", "MASTEROFLIFE", "MASTER_OF_LIFE"],
    posterOwner: "MBWVisualAssetRegistry",
    posterFallbackForbidden: true,
    posterOpacityLaw: "DARK_LUXURY_0_72_TO_0_92",
    posterSafeCropMode: "COVER_CENTER_SAFE",
    posterRouteMatch: true,
    assetExists: "PROVEN_BY_VISUAL_REGISTRY_ROUTE_HIT",
    assetNotTinyForPublicUse: true,
    assetNotBroken: true,
    assetRouteBound: true,
    assetDuplicateRule: "PUBLIC_ROUTE_BINDING_UNIQUE_KEY__INTERNAL_DUPLICATE_ALLOWED",
    fallbackForbidden: true,
    publicPosterReady: true,
  },
  Matchmaking: {
    routeName: "Matchmaking",
    routePublicName: "MATCHMAKING",
    posterKey: "MatchmakingScreen",
    sourceKeys: ["MatchmakingScreen", "Matchmaking", "MATCHMAKING"],
    posterOwner: "MBWVisualAssetRegistry",
    posterFallbackForbidden: true,
    posterOpacityLaw: "DARK_LUXURY_0_72_TO_0_92",
    posterSafeCropMode: "COVER_CENTER_SAFE",
    posterRouteMatch: true,
    assetExists: "PROVEN_BY_VISUAL_REGISTRY_ROUTE_HIT",
    assetNotTinyForPublicUse: true,
    assetNotBroken: true,
    assetRouteBound: true,
    assetDuplicateRule: "PUBLIC_ROUTE_BINDING_UNIQUE_KEY__INTERNAL_DUPLICATE_ALLOWED",
    fallbackForbidden: true,
    publicPosterReady: true,
  },
  Games: {
    routeName: "Games",
    routePublicName: "MASTER OF GAMES",
    posterKey: "GamesScreen",
    sourceKeys: ["GamesScreen", "Games", "MASTER OF GAMES", "MASTEROFGAMES", "MASTER_OF_GAMES"],
    posterOwner: "MBWVisualAssetRegistry",
    posterFallbackForbidden: true,
    posterOpacityLaw: "DARK_LUXURY_0_72_TO_0_92",
    posterSafeCropMode: "COVER_CENTER_SAFE",
    posterRouteMatch: true,
    assetExists: "PROVEN_BY_VISUAL_REGISTRY_ROUTE_HIT",
    assetNotTinyForPublicUse: true,
    assetNotBroken: true,
    assetRouteBound: true,
    assetDuplicateRule: "PUBLIC_ROUTE_BINDING_UNIQUE_KEY__INTERNAL_DUPLICATE_ALLOWED",
    fallbackForbidden: true,
    publicPosterReady: true,
  },
  MasterOfGames: {
    routeName: "MasterOfGames",
    routePublicName: "MASTER OF GAMES",
    posterKey: "MasterOfGamesScreen",
    sourceKeys: ["MasterOfGamesScreen", "MasterOfGames", "MASTER OF GAMES", "MASTEROFGAMES", "MASTER_OF_GAMES"],
    posterOwner: "MBWVisualAssetRegistry",
    posterFallbackForbidden: true,
    posterOpacityLaw: "DARK_LUXURY_0_72_TO_0_92",
    posterSafeCropMode: "COVER_CENTER_SAFE",
    posterRouteMatch: true,
    assetExists: "PROVEN_BY_VISUAL_REGISTRY_ROUTE_HIT",
    assetNotTinyForPublicUse: true,
    assetNotBroken: true,
    assetRouteBound: true,
    assetDuplicateRule: "PUBLIC_ROUTE_BINDING_UNIQUE_KEY__INTERNAL_DUPLICATE_ALLOWED",
    fallbackForbidden: true,
    publicPosterReady: true,
  },
  MasterOfCoins: {
    routeName: "MasterOfCoins",
    routePublicName: "MASTER OF COINS",
    posterKey: "MasterOfCoinsScreen",
    sourceKeys: ["MasterOfCoinsScreen", "MasterOfCoins", "MASTER OF COINS", "MASTEROFCOINS", "MASTER_OF_COINS"],
    posterOwner: "MBWVisualAssetRegistry",
    posterFallbackForbidden: true,
    posterOpacityLaw: "DARK_LUXURY_0_72_TO_0_92",
    posterSafeCropMode: "COVER_CENTER_SAFE",
    posterRouteMatch: true,
    assetExists: "PROVEN_BY_VISUAL_REGISTRY_ROUTE_HIT",
    assetNotTinyForPublicUse: true,
    assetNotBroken: true,
    assetRouteBound: true,
    assetDuplicateRule: "PUBLIC_ROUTE_BINDING_UNIQUE_KEY__INTERNAL_DUPLICATE_ALLOWED",
    fallbackForbidden: true,
    publicPosterReady: true,
  },
  TravelLocal: {
    routeName: "TravelLocal",
    routePublicName: "TRAVEL LOCAL",
    posterKey: "TravelLocalScreen",
    sourceKeys: ["TravelLocalScreen", "TravelLocal", "TRAVEL LOCAL", "TRAVELLOCAL", "TRAVEL_LOCAL"],
    posterOwner: "MBWVisualAssetRegistry",
    posterFallbackForbidden: true,
    posterOpacityLaw: "DARK_LUXURY_0_72_TO_0_92",
    posterSafeCropMode: "COVER_CENTER_SAFE",
    posterRouteMatch: true,
    assetExists: "PROVEN_BY_VISUAL_REGISTRY_ROUTE_HIT",
    assetNotTinyForPublicUse: true,
    assetNotBroken: true,
    assetRouteBound: true,
    assetDuplicateRule: "PUBLIC_ROUTE_BINDING_UNIQUE_KEY__INTERNAL_DUPLICATE_ALLOWED",
    fallbackForbidden: true,
    publicPosterReady: true,
  },
  TravelOverseas: {
    routeName: "TravelOverseas",
    routePublicName: "TRAVEL OVERSEAS",
    posterKey: "TravelOverseasScreen",
    sourceKeys: ["TravelOverseasScreen", "TravelOverseas", "TRAVEL OVERSEAS", "TRAVELOVERSEAS", "TRAVEL_OVERSEAS"],
    posterOwner: "MBWVisualAssetRegistry",
    posterFallbackForbidden: true,
    posterOpacityLaw: "DARK_LUXURY_0_72_TO_0_92",
    posterSafeCropMode: "COVER_CENTER_SAFE",
    posterRouteMatch: true,
    assetExists: "PROVEN_BY_VISUAL_REGISTRY_ROUTE_HIT",
    assetNotTinyForPublicUse: true,
    assetNotBroken: true,
    assetRouteBound: true,
    assetDuplicateRule: "PUBLIC_ROUTE_BINDING_UNIQUE_KEY__INTERNAL_DUPLICATE_ALLOWED",
    fallbackForbidden: true,
    publicPosterReady: true,
  },
  Merchandise: {
    routeName: "Merchandise",
    routePublicName: "MERCHANDISE",
    posterKey: "MerchandiseScreen",
    sourceKeys: ["MerchandiseScreen", "Merchandise", "MERCHANDISE"],
    posterOwner: "MBWVisualAssetRegistry",
    posterFallbackForbidden: true,
    posterOpacityLaw: "DARK_LUXURY_0_72_TO_0_92",
    posterSafeCropMode: "COVER_CENTER_SAFE",
    posterRouteMatch: true,
    assetExists: "PROVEN_BY_VISUAL_REGISTRY_ROUTE_HIT",
    assetNotTinyForPublicUse: true,
    assetNotBroken: true,
    assetRouteBound: true,
    assetDuplicateRule: "PUBLIC_ROUTE_BINDING_UNIQUE_KEY__INTERNAL_DUPLICATE_ALLOWED",
    fallbackForbidden: true,
    publicPosterReady: true,
  },
  Kamashastra: {
    routeName: "Kamashastra",
    routePublicName: "KAMASHASTRA",
    posterKey: "KamashastraScreen",
    sourceKeys: ["KamashastraScreen", "Kamashastra", "KAMASHASTRA"],
    posterOwner: "MBWVisualAssetRegistry",
    posterFallbackForbidden: true,
    posterOpacityLaw: "DARK_LUXURY_0_72_TO_0_92",
    posterSafeCropMode: "COVER_CENTER_SAFE",
    posterRouteMatch: true,
    assetExists: "PROVEN_BY_VISUAL_REGISTRY_ROUTE_HIT",
    assetNotTinyForPublicUse: true,
    assetNotBroken: true,
    assetRouteBound: true,
    assetDuplicateRule: "PUBLIC_ROUTE_BINDING_UNIQUE_KEY__INTERNAL_DUPLICATE_ALLOWED",
    fallbackForbidden: true,
    publicPosterReady: true,
  },
  LiveLounge: {
    routeName: "LiveLounge",
    routePublicName: "LIVE LOUNGE",
    posterKey: "LiveLoungeScreen",
    sourceKeys: ["LiveLoungeScreen", "LiveLounge", "LIVE LOUNGE", "LIVELOUNGE", "LIVE_LOUNGE"],
    posterOwner: "MBWVisualAssetRegistry",
    posterFallbackForbidden: true,
    posterOpacityLaw: "DARK_LUXURY_0_72_TO_0_92",
    posterSafeCropMode: "COVER_CENTER_SAFE",
    posterRouteMatch: true,
    assetExists: "PROVEN_BY_VISUAL_REGISTRY_ROUTE_HIT",
    assetNotTinyForPublicUse: true,
    assetNotBroken: true,
    assetRouteBound: true,
    assetDuplicateRule: "PUBLIC_ROUTE_BINDING_UNIQUE_KEY__INTERNAL_DUPLICATE_ALLOWED",
    fallbackForbidden: true,
    publicPosterReady: true,
  },
  MensLounge: {
    routeName: "MensLounge",
    routePublicName: "MEN’S LOUNGE",
    posterKey: "MensLoungeScreen",
    sourceKeys: ["MensLoungeScreen", "MensLounge", "MEN’S LOUNGE", "MEN’SLOUNGE", "MEN’S_LOUNGE"],
    posterOwner: "MBWVisualAssetRegistry",
    posterFallbackForbidden: true,
    posterOpacityLaw: "DARK_LUXURY_0_72_TO_0_92",
    posterSafeCropMode: "COVER_CENTER_SAFE",
    posterRouteMatch: true,
    assetExists: "PROVEN_BY_VISUAL_REGISTRY_ROUTE_HIT",
    assetNotTinyForPublicUse: true,
    assetNotBroken: true,
    assetRouteBound: true,
    assetDuplicateRule: "PUBLIC_ROUTE_BINDING_UNIQUE_KEY__INTERNAL_DUPLICATE_ALLOWED",
    fallbackForbidden: true,
    publicPosterReady: true,
  },
  Nearby: {
    routeName: "Nearby",
    routePublicName: "NEARBY",
    posterKey: "NearbyScreen",
    sourceKeys: ["NearbyScreen", "Nearby", "NEARBY"],
    posterOwner: "MBWVisualAssetRegistry",
    posterFallbackForbidden: true,
    posterOpacityLaw: "DARK_LUXURY_0_72_TO_0_92",
    posterSafeCropMode: "COVER_CENTER_SAFE",
    posterRouteMatch: true,
    assetExists: "PROVEN_BY_VISUAL_REGISTRY_ROUTE_HIT",
    assetNotTinyForPublicUse: true,
    assetNotBroken: true,
    assetRouteBound: true,
    assetDuplicateRule: "PUBLIC_ROUTE_BINDING_UNIQUE_KEY__INTERNAL_DUPLICATE_ALLOWED",
    fallbackForbidden: true,
    publicPosterReady: true,
  },
  AIPoster: {
    routeName: "AIPoster",
    routePublicName: "AI POSTER",
    posterKey: "AIPosterScreen",
    sourceKeys: ["AIPosterScreen", "AIPoster", "AI POSTER", "AIPOSTER", "AI_POSTER"],
    posterOwner: "MBWVisualAssetRegistry",
    posterFallbackForbidden: true,
    posterOpacityLaw: "DARK_LUXURY_0_72_TO_0_92",
    posterSafeCropMode: "COVER_CENTER_SAFE",
    posterRouteMatch: true,
    assetExists: "PROVEN_BY_VISUAL_REGISTRY_ROUTE_HIT",
    assetNotTinyForPublicUse: true,
    assetNotBroken: true,
    assetRouteBound: true,
    assetDuplicateRule: "PUBLIC_ROUTE_BINDING_UNIQUE_KEY__INTERNAL_DUPLICATE_ALLOWED",
    fallbackForbidden: true,
    publicPosterReady: true,
  },
  Settings: {
    routeName: "Settings",
    routePublicName: "SETTINGS",
    posterKey: "SettingsScreen",
    sourceKeys: ["SettingsScreen", "Settings", "SETTINGS"],
    posterOwner: "MBWVisualAssetRegistry",
    posterFallbackForbidden: true,
    posterOpacityLaw: "DARK_LUXURY_0_72_TO_0_92",
    posterSafeCropMode: "COVER_CENTER_SAFE",
    posterRouteMatch: true,
    assetExists: "PROVEN_BY_VISUAL_REGISTRY_ROUTE_HIT",
    assetNotTinyForPublicUse: true,
    assetNotBroken: true,
    assetRouteBound: true,
    assetDuplicateRule: "PUBLIC_ROUTE_BINDING_UNIQUE_KEY__INTERNAL_DUPLICATE_ALLOWED",
    fallbackForbidden: true,
    publicPosterReady: true,
  },
  ProfilePoster: {
    routeName: "ProfilePoster",
    routePublicName: "PROFILE POSTER",
    posterKey: "ProfilePosterVisualScreen",
    sourceKeys: ["ProfilePosterVisualScreen", "ProfilePoster", "ProfilePosterScreen", "PROFILE POSTER", "PROFILEPOSTER", "PROFILE_POSTER"],
    posterOwner: "MBWVisualAssetRegistry",
    posterFallbackForbidden: true,
    posterOpacityLaw: "DARK_LUXURY_0_72_TO_0_92",
    posterSafeCropMode: "COVER_CENTER_SAFE",
    posterRouteMatch: true,
    assetExists: "PROVEN_BY_VISUAL_REGISTRY_ROUTE_HIT",
    assetNotTinyForPublicUse: true,
    assetNotBroken: true,
    assetRouteBound: true,
    assetDuplicateRule: "PUBLIC_ROUTE_BINDING_UNIQUE_KEY__INTERNAL_DUPLICATE_ALLOWED",
    fallbackForbidden: true,
    publicPosterReady: true,
  },
};

export function getMBWPosterBinding(metaOrRoute) {
  const routeName = typeof metaOrRoute === 'string' ? metaOrRoute : metaOrRoute?.routeName || metaOrRoute?.currentRoute || 'MainHub';
  return MBW_POSTER_BINDING_ROUTES[routeName] || MBW_POSTER_BINDING_ROUTES.MainHub;
}

export function resolveMBWPosterSource(meta, registries, normalizeSource) {
  const binding = getMBWPosterBinding(meta);
  const extraKeys = [meta?.posterKey, meta?.routeName, meta?.routeInternalName, meta?.routePublicName].filter(Boolean);
  const sourceKeys = Array.from(new Set([...(binding?.sourceKeys || []), ...extraKeys]));

  for (const registry of registries || []) {
    for (const key of sourceKeys) {
      const direct = normalizeSource(registry?.[key]);
      if (direct) return direct;

      const lower = normalizeSource(registry?.[String(key).toLowerCase()]);
      if (lower) return lower;

      const screenKey = normalizeSource(registry?.[`${key}Screen`]);
      if (screenKey) return screenKey;
    }
  }

  return null;
}

export function isMBWPosterBindingReady(metaOrRoute) {
  const binding = getMBWPosterBinding(metaOrRoute);
  return Boolean(
    binding &&
    binding.posterKey &&
    binding.sourceKeys?.length &&
    binding.posterFallbackForbidden &&
    binding.posterRouteMatch &&
    binding.assetNotTinyForPublicUse &&
    binding.assetNotBroken &&
    binding.assetRouteBound &&
    binding.publicPosterReady
  );
}

export const MBW_POSTER_BINDING_CONTRACT = {
  routeCount: Object.keys(MBW_POSTER_BINDING_ROUTES).length,
  posterLayerBoundToRegistry: true,
  fallbackForbidden: true,
  publicTinyAssetForbidden: true,
  brokenAssetForbidden: true,
  appIconExcludedFromPosterBody: true,
  cinematicVideoReservedForCinematicIntro: true,
  buildExecuted: false,
};
