// Generated by MBW 8-command healing package.
export const MBW_CANONICAL_POSTER_REGISTRY = Object.freeze({
  "CinematicIntro": require("../assets/mbw_clean_shuffled_visual_body_posters/CinematicIntroScreen.jpg"),
  "GateLocked": require("../assets/mbw_clean_shuffled_visual_body_posters/GateLockedScreen.jpg"),
  "GateOpen": require("../assets/mbw_clean_shuffled_visual_body_posters/GateOpenScreen.jpg"),
  "PathSelection": require("../assets/mbw_clean_shuffled_visual_body_posters/PathSelectionScreen.jpg"),
  "SubscriptionSignup": require("../assets/mbw_clean_shuffled_visual_body_posters/SubscriptionSignupScreen.jpg"),
  "MainHub": require("../assets/mbw_clean_shuffled_visual_body_posters/MainHubScreen.jpg"),
  "MasterOfLife": require("../assets/mbw_clean_shuffled_visual_body_posters/MasterOfLifeScreen.jpg"),
  "Matchmaking": require("../assets/mbw_clean_shuffled_visual_body_posters/MatchmakingScreen.jpg"),
  "Games": require("../assets/mbw_clean_shuffled_visual_body_posters/GamesScreen.jpg"),
  "MasterOfGames": require("../assets/mbw_clean_shuffled_visual_body_posters/SettingsScreen.jpg"),
  "MasterOfCoins": require("../assets/mbw_clean_shuffled_visual_body_posters/MasterOfCoinsScreen.jpg"),
  "TravelLocal": require("../assets/mbw_clean_shuffled_visual_body_posters/TravelLocalScreen.jpg"),
  "TravelOverseas": require("../assets/mbw_clean_shuffled_visual_body_posters/TravelOverseasScreen.jpg"),
  "Merchandise": require("../assets/mbw_clean_shuffled_visual_body_posters/MerchandiseScreen.jpg"),
  "Kamashastra": require("../assets/mbw_clean_shuffled_visual_body_posters/KamashastraScreen.jpg"),
  "LiveLounge": require("../assets/mbw_clean_shuffled_visual_body_posters/LiveLoungeScreen.jpg"),
  "MensLounge": require("../assets/mbw_clean_shuffled_visual_body_posters/MensLoungeScreen.jpg"),
  "Nearby": require("../assets/mbw_clean_shuffled_visual_body_posters/NearbyScreen.jpg"),
  "AIPoster": require("../assets/mbw_clean_shuffled_visual_body_posters/GamesPosterScreen.jpg"),
  "Settings": require("../assets/mbw_posters/Settings/Settings.png"),
  "ProfilePoster": require("../assets/mbw_clean_shuffled_visual_body_posters/ProfilePosterScreen.jpg"),
});

export function getMBWPosterForScreen(routeName) {
  return MBW_CANONICAL_POSTER_REGISTRY[routeName]
    || MBW_CANONICAL_POSTER_REGISTRY.MainHub;
}

export function resolveMBWFinalVisualRoute(routeName) {
  return Object.freeze({
    routeName,
    poster: getMBWPosterForScreen(routeName),
  });
}

export const resolveMBWVisualRoute = resolveMBWFinalVisualRoute;
export const resolveMBWPosterForRoute = getMBWPosterForScreen;
export default MBW_CANONICAL_POSTER_REGISTRY;
