const MBW_Q_BUILDER_VISUAL_LAW = "MBW_Q_BUILDER_VISUAL_LAW_8D4_TWO_STAGE_GATE";
const MBW_FINAL_PRODUCT_BODY_MD_OWNER = true;
const MBW_BUILD_REQUIRES_LIVE_VISUAL_PROOF = true;
const MBW_BUILD_ALLOWED_ONLY_BY_Q_BUILDER = true;
const MBW_MAINHUB_PARENT_CHILD_FAMILY_PROOF_REQUIRED = true;
const MBW_DYNAMIC_CHILD_ROUTE_PROOF_REQUIRED = true;
const MBW_TWO_STAGE_BUILD_GATE_REQUIRED = true;
const MBW_PREBUILD_GATE_DOES_NOT_REQUIRE_LIVE_SCREENSHOT = true;
const MBW_POSTBUILD_TRUE_GREEN_REQUIRES_LIVE_SCREENSHOT = true;

const MBW_RELEASE_VERSION_NAME = "1.0.42";
const MBW_RELEASE_VERSION_CODE = "44";
const RUNTIME_VERSION_LABEL = "appVersion";
const MBW_RELEASE_VERSION = "MBW_RELEASE_VERSION_1.0.42_CODE_44_APPVERSION";
const MBW_Q_BUILDER_BUNDLE_VERSION_PROOF = "MBWReleaseIdentitySeal__RUNTIME_VERSION_LABEL__MBW_RELEASE_VERSION__1.0.42__appVersion";

const MBW_Q_BUILDER_RELEASE_SEAL = {
  mode: "8D4_TWO_STAGE_GATE",
  versionName: MBW_RELEASE_VERSION_NAME,
  versionCode: MBW_RELEASE_VERSION_CODE,
  packageName: "com.mbw.app",
  runtimeVersionPolicy: RUNTIME_VERSION_LABEL,
  versionProof: MBW_Q_BUILDER_BUNDLE_VERSION_PROOF,
  buildType: "apk",
  aabBuild: false,
  requires: [
    "source_root_proof",
    "runtime_root_proof",
    "md_final_body_law",
    "route_owner_proof",
    "mainhub_parent_proof",
    "mainhub_full_child_family_proof",
    "visual_body_proof",
    "export_bundle_proof",
    "live_visual_proof"
  ],
  trueGreenRequires: [
    "apk_forensic_proof",
    "live_visual_proof",
    "logcat_proof"
  ],
};

global.MBW_Q_BUILDER_VISUAL_LAW = MBW_Q_BUILDER_VISUAL_LAW;
global.MBW_FINAL_PRODUCT_BODY_MD_OWNER = MBW_FINAL_PRODUCT_BODY_MD_OWNER;
global.MBW_BUILD_REQUIRES_LIVE_VISUAL_PROOF = MBW_BUILD_REQUIRES_LIVE_VISUAL_PROOF;
global.MBW_BUILD_ALLOWED_ONLY_BY_Q_BUILDER = MBW_BUILD_ALLOWED_ONLY_BY_Q_BUILDER;
global.MBW_MAINHUB_PARENT_CHILD_FAMILY_PROOF_REQUIRED = MBW_MAINHUB_PARENT_CHILD_FAMILY_PROOF_REQUIRED;
global.MBW_DYNAMIC_CHILD_ROUTE_PROOF_REQUIRED = MBW_DYNAMIC_CHILD_ROUTE_PROOF_REQUIRED;
global.MBW_TWO_STAGE_BUILD_GATE_REQUIRED = MBW_TWO_STAGE_BUILD_GATE_REQUIRED;
global.MBW_PREBUILD_GATE_DOES_NOT_REQUIRE_LIVE_SCREENSHOT = MBW_PREBUILD_GATE_DOES_NOT_REQUIRE_LIVE_SCREENSHOT;
global.MBW_POSTBUILD_TRUE_GREEN_REQUIRES_LIVE_SCREENSHOT = MBW_POSTBUILD_TRUE_GREEN_REQUIRES_LIVE_SCREENSHOT;

global.MBW_RELEASE_VERSION_NAME = MBW_RELEASE_VERSION_NAME;
global.MBW_RELEASE_VERSION_CODE = MBW_RELEASE_VERSION_CODE;
global.RUNTIME_VERSION_LABEL = RUNTIME_VERSION_LABEL;
global.MBW_RELEASE_VERSION = MBW_RELEASE_VERSION;
global.MBW_Q_BUILDER_BUNDLE_VERSION_PROOF = MBW_Q_BUILDER_BUNDLE_VERSION_PROOF;
global.MBW_Q_BUILDER_RELEASE_SEAL = MBW_Q_BUILDER_RELEASE_SEAL;

module.exports = {
  MBW_Q_BUILDER_VISUAL_LAW,
  MBW_FINAL_PRODUCT_BODY_MD_OWNER,
  MBW_BUILD_REQUIRES_LIVE_VISUAL_PROOF,
  MBW_BUILD_ALLOWED_ONLY_BY_Q_BUILDER,
  MBW_MAINHUB_PARENT_CHILD_FAMILY_PROOF_REQUIRED,
  MBW_DYNAMIC_CHILD_ROUTE_PROOF_REQUIRED,

  MBW_TWO_STAGE_BUILD_GATE_REQUIRED,
  MBW_PREBUILD_GATE_DOES_NOT_REQUIRE_LIVE_SCREENSHOT,
  MBW_POSTBUILD_TRUE_GREEN_REQUIRES_LIVE_SCREENSHOT,

  MBW_RELEASE_VERSION_NAME,
  MBW_RELEASE_VERSION_CODE,
  RUNTIME_VERSION_LABEL,
  MBW_RELEASE_VERSION,
  MBW_Q_BUILDER_BUNDLE_VERSION_PROOF,
  MBW_Q_BUILDER_RELEASE_SEAL,
};
