// MBW 18ZZF HARDEST-FIRST 105 POSTER REMAP
// Round 1 places all 105 proper pad posters once.
// Hardest poster sources are assigned first to preserve exact/category slots.
// Generated-renamed posters are support-slot only.
// Controlled support slot is audit-only and never zero-score.
// Remaining routes reuse the same 105 pool through category-aware shuffle.
// Live UI renders appearing/disappearing headline, floating icon buttons, motion, and eating-word labels.

export const MBW_SCREEN_POSTERS = {
  "ArcadeHubScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/ArcadeHubScreen.jpg"),
  "CinematicIntroScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/CinematicIntroScreen.jpg"),
  "DashboardScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/DashboardScreen.jpg"),
  "GamesActionScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/GamesActionScreen.jpg"),
  "GamesAssetsScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/GamesAssetsScreen.jpg"),
  "GamesButtonsScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/GamesButtonsScreen.jpg"),
  "GamesEntryScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/GamesEntryScreen.jpg"),
  "GamesLiveScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/GamesLiveScreen.jpg"),
  "GamesLogicScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/GamesLogicScreen.jpg"),
  "GamesMotionScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/GamesMotionScreen.jpg"),
  "GamesOverviewScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/GamesOverviewScreen.jpg"),
  "GamesPanchTatvaScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/GamesPanchTatvaScreen.jpg"),
  "GamesPosterScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/GamesPosterScreen.jpg"),
  "GamesProofScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/GamesProofScreen.jpg"),
  "GamesResultScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/GamesResultScreen.jpg"),
  "GamesReturnScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/GamesReturnScreen.jpg"),
  "GamesScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/GamesScreen.jpg"),
  "GamesSeedScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/GamesSeedScreen.jpg"),
  "GamesStateScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/GamesStateScreen.jpg"),
  "GamesVaultScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/GamesVaultScreen.jpg"),
  "GateLockedScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/GateLockedScreen.jpg"),
  "GateOpenScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/GateOpenScreen.jpg"),
  "KamashastraActionScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/KamashastraActionScreen.jpg"),
  "KamashastraAssetsScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/KamashastraAssetsScreen.jpg"),
  "KamashastraButtonsScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/KamashastraButtonsScreen.jpg"),
  "KamashastraEntryScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/KamashastraEntryScreen.jpg"),
  "KamashastraLiveScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/KamashastraLiveScreen.jpg"),
  "KamashastraLogicScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/KamashastraLogicScreen.jpg"),
  "KamashastraMotionScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/KamashastraMotionScreen.jpg"),
  "KamashastraOverviewScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/KamashastraOverviewScreen.jpg"),
  "KamashastraPanchTatvaScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/KamashastraPanchTatvaScreen.jpg"),
  "KamashastraPosterScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/KamashastraPosterScreen.jpg"),
  "KamashastraProofScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/KamashastraProofScreen.jpg"),
  "KamashastraResultScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/KamashastraResultScreen.jpg"),
  "KamashastraReturnScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/KamashastraReturnScreen.jpg"),
  "KamashastraScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/KamashastraScreen.jpg"),
  "KamashastraSeedScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/KamashastraSeedScreen.jpg"),
  "KamashastraStateScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/KamashastraStateScreen.jpg"),
  "KamashastraVaultScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/KamashastraVaultScreen.jpg"),
  "LiveLoungeActionScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/LiveLoungeActionScreen.jpg"),
  "LiveLoungeAssetsScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/LiveLoungeAssetsScreen.jpg"),
  "LiveLoungeButtonsScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/LiveLoungeButtonsScreen.jpg"),
  "LiveLoungeEntryScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/LiveLoungeEntryScreen.jpg"),
  "LiveLoungeLiveScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/LiveLoungeLiveScreen.jpg"),
  "LiveLoungeLogicScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/LiveLoungeLogicScreen.jpg"),
  "LiveLoungeMotionScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/LiveLoungeMotionScreen.jpg"),
  "LiveLoungeOverviewScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/LiveLoungeOverviewScreen.jpg"),
  "LiveLoungePanchTatvaScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/LiveLoungePanchTatvaScreen.jpg"),
  "LiveLoungePosterScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/LiveLoungePosterScreen.jpg"),
  "LiveLoungeProofScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/LiveLoungeProofScreen.jpg"),
  "LiveLoungeResultScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/LiveLoungeResultScreen.jpg"),
  "LiveLoungeReturnScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/LiveLoungeReturnScreen.jpg"),
  "LiveLoungeScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/LiveLoungeScreen.jpg"),
  "LiveLoungeSeedScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/LiveLoungeSeedScreen.jpg"),
  "LiveLoungeStateScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/LiveLoungeStateScreen.jpg"),
  "LiveLoungeVaultScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/LiveLoungeVaultScreen.jpg"),
  "MBWOSRuntimeCarryScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MBWOSRuntimeCarryScreen.jpg"),
  "MBWRouteProofScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MBWRouteProofScreen.jpg"),
  "MainHubScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MainHubScreen.jpg"),
  "MasterOfCoinsActionScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MasterOfCoinsActionScreen.jpg"),
  "MasterOfCoinsAssetsScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MasterOfCoinsAssetsScreen.jpg"),
  "MasterOfCoinsButtonsScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MasterOfCoinsButtonsScreen.jpg"),
  "MasterOfCoinsEntryScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MasterOfCoinsEntryScreen.jpg"),
  "MasterOfCoinsLiveScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MasterOfCoinsLiveScreen.jpg"),
  "MasterOfCoinsLogicScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MasterOfCoinsLogicScreen.jpg"),
  "MasterOfCoinsMotionScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MasterOfCoinsMotionScreen.jpg"),
  "MasterOfCoinsOverviewScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MasterOfCoinsOverviewScreen.jpg"),
  "MasterOfCoinsPanchTatvaScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MasterOfCoinsPanchTatvaScreen.jpg"),
  "MasterOfCoinsPosterScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MasterOfCoinsPosterScreen.jpg"),
  "MasterOfCoinsProofScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MasterOfCoinsProofScreen.jpg"),
  "MasterOfCoinsResultScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MasterOfCoinsResultScreen.jpg"),
  "MasterOfCoinsReturnScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MasterOfCoinsReturnScreen.jpg"),
  "MasterOfCoinsScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MasterOfCoinsScreen.jpg"),
  "MasterOfCoinsSeedScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MasterOfCoinsSeedScreen.jpg"),
  "MasterOfCoinsStateScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MasterOfCoinsStateScreen.jpg"),
  "MasterOfCoinsVaultScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MasterOfCoinsVaultScreen.jpg"),
  "MasterOfLifeActionScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MasterOfLifeActionScreen.jpg"),
  "MasterOfLifeAssetsScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MasterOfLifeAssetsScreen.jpg"),
  "MasterOfLifeButtonsScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MasterOfLifeButtonsScreen.jpg"),
  "MasterOfLifeEntryScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MasterOfLifeEntryScreen.jpg"),
  "MasterOfLifeLiveScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MasterOfLifeLiveScreen.jpg"),
  "MasterOfLifeLogicScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MasterOfLifeLogicScreen.jpg"),
  "MasterOfLifeMotionScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MasterOfLifeMotionScreen.jpg"),
  "MasterOfLifeOverviewScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MasterOfLifeOverviewScreen.jpg"),
  "MasterOfLifePanchTatvaScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MasterOfLifePanchTatvaScreen.jpg"),
  "MasterOfLifePosterScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MasterOfLifePosterScreen.jpg"),
  "MasterOfLifeProofScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MasterOfLifeProofScreen.jpg"),
  "MasterOfLifeResultScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MasterOfLifeResultScreen.jpg"),
  "MasterOfLifeReturnScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MasterOfLifeReturnScreen.jpg"),
  "MasterOfLifeScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MasterOfLifeScreen.jpg"),
  "MasterOfLifeSeedScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MasterOfLifeSeedScreen.jpg"),
  "MasterOfLifeStateScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MasterOfLifeStateScreen.jpg"),
  "MasterOfLifeVaultScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MasterOfLifeVaultScreen.jpg"),
  "MatchFinalReincarnationScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MatchFinalReincarnationScreen.jpg"),
  "MatchmakingActionScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MatchmakingActionScreen.jpg"),
  "MatchmakingAssetsScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MatchmakingAssetsScreen.jpg"),
  "MatchmakingButtonsScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MatchmakingButtonsScreen.jpg"),
  "MatchmakingEntryScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MatchmakingEntryScreen.jpg"),
  "MatchmakingLiveScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MatchmakingLiveScreen.jpg"),
  "MatchmakingLogicScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MatchmakingLogicScreen.jpg"),
  "MatchmakingMotionScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MatchmakingMotionScreen.jpg"),
  "MatchmakingOverviewScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MatchmakingOverviewScreen.jpg"),
  "MatchmakingPanchTatvaScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MatchmakingPanchTatvaScreen.jpg"),
  "MatchmakingPosterScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MatchmakingPosterScreen.jpg"),
  "MatchmakingProofScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MatchmakingProofScreen.jpg"),
  "MatchmakingResultScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MatchmakingResultScreen.jpg"),
  "MatchmakingReturnScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MatchmakingReturnScreen.jpg"),
  "MatchmakingScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MatchmakingScreen.jpg"),
  "MatchmakingSeedScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MatchmakingSeedScreen.jpg"),
  "MatchmakingStateScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MatchmakingStateScreen.jpg"),
  "MatchmakingVaultScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MatchmakingVaultScreen.jpg"),
  "MensLoungeActionScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MensLoungeActionScreen.jpg"),
  "MensLoungeAssetsScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MensLoungeAssetsScreen.jpg"),
  "MensLoungeButtonsScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MensLoungeButtonsScreen.jpg"),
  "MensLoungeEntryScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MensLoungeEntryScreen.jpg"),
  "MensLoungeLiveScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MensLoungeLiveScreen.jpg"),
  "MensLoungeLogicScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MensLoungeLogicScreen.jpg"),
  "MensLoungeMotionScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MensLoungeMotionScreen.jpg"),
  "MensLoungeOverviewScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MensLoungeOverviewScreen.jpg"),
  "MensLoungePanchTatvaScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MensLoungePanchTatvaScreen.jpg"),
  "MensLoungePosterScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MensLoungePosterScreen.jpg"),
  "MensLoungeProofScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MensLoungeProofScreen.jpg"),
  "MensLoungeResultScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MensLoungeResultScreen.jpg"),
  "MensLoungeReturnScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MensLoungeReturnScreen.jpg"),
  "MensLoungeScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MensLoungeScreen.jpg"),
  "MensLoungeSeedScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MensLoungeSeedScreen.jpg"),
  "MensLoungeStateScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MensLoungeStateScreen.jpg"),
  "MensLoungeVaultScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MensLoungeVaultScreen.jpg"),
  "MerchandiseActionScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MerchandiseActionScreen.jpg"),
  "MerchandiseAssetsScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MerchandiseAssetsScreen.jpg"),
  "MerchandiseButtonsScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MerchandiseButtonsScreen.jpg"),
  "MerchandiseEntryScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MerchandiseEntryScreen.jpg"),
  "MerchandiseLiveScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MerchandiseLiveScreen.jpg"),
  "MerchandiseLogicScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MerchandiseLogicScreen.jpg"),
  "MerchandiseMotionScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MerchandiseMotionScreen.jpg"),
  "MerchandiseOverviewScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MerchandiseOverviewScreen.jpg"),
  "MerchandisePanchTatvaScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MerchandisePanchTatvaScreen.jpg"),
  "MerchandisePosterScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MerchandisePosterScreen.jpg"),
  "MerchandiseProofScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MerchandiseProofScreen.jpg"),
  "MerchandiseResultScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MerchandiseResultScreen.jpg"),
  "MerchandiseReturnScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MerchandiseReturnScreen.jpg"),
  "MerchandiseScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MerchandiseScreen.jpg"),
  "MerchandiseSeedScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MerchandiseSeedScreen.jpg"),
  "MerchandiseStateScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MerchandiseStateScreen.jpg"),
  "MerchandiseVaultScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/MerchandiseVaultScreen.jpg"),
  "NearbyActionScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/NearbyActionScreen.jpg"),
  "NearbyAssetsScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/NearbyAssetsScreen.jpg"),
  "NearbyButtonsScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/NearbyButtonsScreen.jpg"),
  "NearbyEntryScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/NearbyEntryScreen.jpg"),
  "NearbyLiveScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/NearbyLiveScreen.jpg"),
  "NearbyLogicScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/NearbyLogicScreen.jpg"),
  "NearbyMotionScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/NearbyMotionScreen.jpg"),
  "NearbyOverviewScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/NearbyOverviewScreen.jpg"),
  "NearbyPanchTatvaScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/NearbyPanchTatvaScreen.jpg"),
  "NearbyPosterScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/NearbyPosterScreen.jpg"),
  "NearbyProofScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/NearbyProofScreen.jpg"),
  "NearbyResultScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/NearbyResultScreen.jpg"),
  "NearbyReturnScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/NearbyReturnScreen.jpg"),
  "NearbyScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/NearbyScreen.jpg"),
  "NearbySeedScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/NearbySeedScreen.jpg"),
  "NearbyStateScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/NearbyStateScreen.jpg"),
  "NearbyVaultScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/NearbyVaultScreen.jpg"),
  "PathSelectionScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/PathSelectionScreen.jpg"),
  "PentagramArcadeScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/PentagramArcadeScreen.jpg"),
  "ProfilePosterActionScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/ProfilePosterActionScreen.jpg"),
  "ProfilePosterAssetsScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/ProfilePosterAssetsScreen.jpg"),
  "ProfilePosterButtonsScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/ProfilePosterButtonsScreen.jpg"),
  "ProfilePosterEntryScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/ProfilePosterEntryScreen.jpg"),
  "ProfilePosterLiveScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/ProfilePosterLiveScreen.jpg"),
  "ProfilePosterLogicScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/ProfilePosterLogicScreen.jpg"),
  "ProfilePosterMotionScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/ProfilePosterMotionScreen.jpg"),
  "ProfilePosterOverviewScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/ProfilePosterOverviewScreen.jpg"),
  "ProfilePosterPanchTatvaScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/ProfilePosterPanchTatvaScreen.jpg"),
  "ProfilePosterPosterScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/ProfilePosterPosterScreen.jpg"),
  "ProfilePosterProofScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/ProfilePosterProofScreen.jpg"),
  "ProfilePosterResultScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/ProfilePosterResultScreen.jpg"),
  "ProfilePosterReturnScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/ProfilePosterReturnScreen.jpg"),
  "ProfilePosterScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/ProfilePosterScreen.jpg"),
  "ProfilePosterSeedScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/ProfilePosterSeedScreen.jpg"),
  "ProfilePosterStateScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/ProfilePosterStateScreen.jpg"),
  "ProfilePosterVaultScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/ProfilePosterVaultScreen.jpg"),
  "SettingsActionScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/SettingsActionScreen.jpg"),
  "SettingsAssetsScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/SettingsAssetsScreen.jpg"),
  "SettingsButtonsScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/SettingsButtonsScreen.jpg"),
  "SettingsEntryScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/SettingsEntryScreen.jpg"),
  "SettingsLiveScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/SettingsLiveScreen.jpg"),
  "SettingsLogicScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/SettingsLogicScreen.jpg"),
  "SettingsMotionScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/SettingsMotionScreen.jpg"),
  "SettingsOverviewScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/SettingsOverviewScreen.jpg"),
  "SettingsPanchTatvaScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/SettingsPanchTatvaScreen.jpg"),
  "SettingsPosterScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/SettingsPosterScreen.jpg"),
  "SettingsProofScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/SettingsProofScreen.jpg"),
  "SettingsResultScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/SettingsResultScreen.jpg"),
  "SettingsReturnScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/SettingsReturnScreen.jpg"),
  "SettingsScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/SettingsScreen.jpg"),
  "SettingsSeedScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/SettingsSeedScreen.jpg"),
  "SettingsStateScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/SettingsStateScreen.jpg"),
  "SettingsVaultScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/SettingsVaultScreen.jpg"),
  "SubscriptionSignupScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/SubscriptionSignupScreen.jpg"),
  "TravelLocalActionScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/TravelLocalActionScreen.jpg"),
  "TravelLocalAssetsScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/TravelLocalAssetsScreen.jpg"),
  "TravelLocalButtonsScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/TravelLocalButtonsScreen.jpg"),
  "TravelLocalEntryScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/TravelLocalEntryScreen.jpg"),
  "TravelLocalLiveScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/TravelLocalLiveScreen.jpg"),
  "TravelLocalLogicScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/TravelLocalLogicScreen.jpg"),
  "TravelLocalMotionScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/TravelLocalMotionScreen.jpg"),
  "TravelLocalOverviewScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/TravelLocalOverviewScreen.jpg"),
  "TravelLocalPanchTatvaScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/TravelLocalPanchTatvaScreen.jpg"),
  "TravelLocalPosterScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/TravelLocalPosterScreen.jpg"),
  "TravelLocalProofScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/TravelLocalProofScreen.jpg"),
  "TravelLocalResultScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/TravelLocalResultScreen.jpg"),
  "TravelLocalReturnScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/TravelLocalReturnScreen.jpg"),
  "TravelLocalScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/TravelLocalScreen.jpg"),
  "TravelLocalSeedScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/TravelLocalSeedScreen.jpg"),
  "TravelLocalStateScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/TravelLocalStateScreen.jpg"),
  "TravelLocalVaultScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/TravelLocalVaultScreen.jpg"),
  "TravelOverseasActionScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/TravelOverseasActionScreen.jpg"),
  "TravelOverseasAssetsScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/TravelOverseasAssetsScreen.jpg"),
  "TravelOverseasButtonsScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/TravelOverseasButtonsScreen.jpg"),
  "TravelOverseasEntryScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/TravelOverseasEntryScreen.jpg"),
  "TravelOverseasLiveScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/TravelOverseasLiveScreen.jpg"),
  "TravelOverseasLogicScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/TravelOverseasLogicScreen.jpg"),
  "TravelOverseasMotionScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/TravelOverseasMotionScreen.jpg"),
  "TravelOverseasOverviewScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/TravelOverseasOverviewScreen.jpg"),
  "TravelOverseasPanchTatvaScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/TravelOverseasPanchTatvaScreen.jpg"),
  "TravelOverseasPosterScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/TravelOverseasPosterScreen.jpg"),
  "TravelOverseasProofScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/TravelOverseasProofScreen.jpg"),
  "TravelOverseasResultScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/TravelOverseasResultScreen.jpg"),
  "TravelOverseasReturnScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/TravelOverseasReturnScreen.jpg"),
  "TravelOverseasScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/TravelOverseasScreen.jpg"),
  "TravelOverseasSeedScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/TravelOverseasSeedScreen.jpg"),
  "TravelOverseasStateScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/TravelOverseasStateScreen.jpg"),
  "TravelOverseasVaultScreen": require("../assets/mbw_clean_shuffled_visual_body_posters/TravelOverseasVaultScreen.jpg"),
};
export function getMBWVisualPolicyForScreen(screenName) {
  const posterSource = MBW_SCREEN_POSTERS[screenName];
  if (!posterSource) {
    throw new Error(`MBW_VISUAL_BODY_SOURCE_READY_${screenName}`);
  }
  return {
    screenName,
    posterSource,
    posterKind: 'HARDEST_FIRST_105_PAD_REMAP_MBW_POSTER',
    cleanPoster: true,
    shuffledPoster: true,
    padStorageSource: true,
    topLevelPadSourceOnly: true,
    properPosterPoolCount: 105,
    firstPassEveryPosterPlacedOnce: true,
    hardestPosterAssignedFirst: true,
    generatedRenameOnlySupportSlot: true,
    controlledSupportSlotOnly: true,
    noZeroScoreFirstPass: true,
    remainingRoutesFilledBySame105CategoryShuffle: true,
    noBakedUi: true,
    noInbuiltUiPoster: true,
    screenOwnedPoster: true,
    exactVisualBody: true,
    liveUiOnly: true,
    uiContract: 'HEADLINE_FLOATING_ICONS_MOTION_EATING_WORDS',
  };
}

export default MBW_SCREEN_POSTERS;

// MBW 18ZZJ CINEMATIC VIDEO HARD WIRE
export const MBW_CINEMATIC_VIDEO_SOURCE = require("../assets/cinematic/mbw_cinematic.mp4");

export const MBW_CINEMATIC_VIDEO_POLICY = {
  cinematicVideoSource: MBW_CINEMATIC_VIDEO_SOURCE,
  cinematicVideoKind: "MBW_GATE_PREFERRED_PAD_VIDEO",
  cinematicVideoRequired: true,
  cinematicVideoLoop: false,
  cinematicVideoMuted: false,
  cinematicVideoResizeMode: "cover",
  cinematicVideoContract: "WELCOME_TO_MBW_UNSKIPPABLE_11_SECONDS",
  padPreferredVideoCopied: true,
  noPosterReplacementForCinematicIntro: true,
};

// MBW 18ZZM COLOR RATIO 1:1:1 HARD POLICY
export const MBW_COLOR_RATIO_POLICY = Object.freeze({
  visualColorContract: "COLOR_RATIO_1_1_1_BLACK_GOLD_MAROON",
  colorRatio: "1:1:1",
  black: "#050205",
  gold: "#D4AF37",
  maroon: "#5A0B18",
  blackGoldMaroon: true,
  dominantColorsOnly: ["black", "gold", "maroon"],
  noOtherDominantColor: true,
});

// MBW_24E18_CRASH_FIX_EXPORT
// Named export required by app/components/MBWSingleAppVisualBody.js
export function getMBWPosterForScreen(screenName) {
  const key = String(screenName || 'MAINHUB').trim();
  try {
    if (typeof MBW_SCREEN_POSTERS !== 'undefined' && MBW_SCREEN_POSTERS) {
      if (Array.isArray(MBW_SCREEN_POSTERS) && MBW_SCREEN_POSTERS.length) return MBW_SCREEN_POSTERS[Math.abs(key.length) % MBW_SCREEN_POSTERS.length];
      if (MBW_SCREEN_POSTERS[key]) return MBW_SCREEN_POSTERS[key];
      const normalized = key.toUpperCase().replace(/[^A-Z0-9]+/g, '_');
      if (MBW_SCREEN_POSTERS[normalized]) return MBW_SCREEN_POSTERS[normalized];
      const values = Object.values(MBW_SCREEN_POSTERS).filter(Boolean);
      if (values.length) return values[Math.abs(key.length) % values.length];
    }
  } catch (e) {}
  return require("../assets/mbw_clean_shuffled_visual_body_posters/ArcadeHubScreen.jpg");
}

